language: java
jdk: oraclejdk8
sudo: false
dist: trusty

env:
  global:
    - PROJECT_DIR=${TRAVIS_BUILD_DIR} # Project directory

notifications:
  email: false

script:
  - cd ${PROJECT_DIR} && mvn clean install

after_script:
  - echo "Test Result -> $TRAVIS_TEST_RESULT"
  - ls -l $TRAVIS_BUILD_DIR/target